[package]
name = "lapse-template"
description = "Lapse template package"
version = { workspace = true }
edition = "2024"
authors = ["Gabriel C. Brandão <biel.brandao2004@gmailcom>"]
repository = "https://github.com/gab1618/lapse"
homepage = "https://github.com/gab1618/lapse"
license = "GPLv3"
exclude = ["assets"]

[dependencies]
lapse = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_yaml = "0.9.34"

[dev-dependencies]
tempfile = { workspace = true }
