[package]
name = "lapse"
version = { workspace = true }
edition = "2024"
authors = ["Gabriel C. Brandão <biel.brandao2004@gmailcom>"]
repository = "https://github.com/gab1618/lapse"
homepage = "https://github.com/gab1618/lapse"
license = "GPLv3"
exclude = ["assets"]

[dependencies]
http = "1.4.2"
mlua = { version = "0.12.0", features = ["lua54", "vendored", "async"] }
reqwest = { version = "0.13.4", features = ["multipart", "stream", "cookies"] }
serde = { workspace = true }
serde_json = "1.0.150"
stream = "0.1.0"
thiserror = {workspace = true}

[dev-dependencies]
tempfile = {workspace = true}
