[package]
name = "lapse-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
clap_complete = "4.6.7"
inquire = "0.9.4"
lapse = { workspace = true }
tokio = { version = "1.52.3", features = ["full"] }
thiserror = { workspace = true }
nucleo-matcher = "0.3.1"
minus = { version = "5.7.2", features = ["static_output"] }

[[bin]]
name = "lapse"
path = "src/main.rs"
